// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AplicacaoBlazor.Models
{
    public partial class TbTarefa
    {
        public int IdTarefa { get; set; }
        public string TaTitulo { get; set; }
        public string TaDescricao { get; set; }
        public string TaStatus { get; set; }
        public int FkUsuario { get; set; }

        public virtual TbUsuario FkUsuarioNavigation { get; set; }
    }
}