// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AplicacaoBlazor.Models
{
    public partial class TbUsuario
    {
        public TbUsuario()
        {
            TbTarefas = new HashSet<TbTarefa>();
        }

        public int IdUsuario { get; set; }
        public string UsNome { get; set; }
        public string UsEmail { get; set; }
        public string UsSenha { get; set; }

        public virtual ICollection<TbTarefa> TbTarefas { get; set; }
    }
}